GHC-118: Build Orthopedic Form
globalhealthcoalition/openmrs-config-ghc pull request #73
Opened 2022-03-07 06:55 UTC by basrem

2022-03-07 07:03 UTC, reagan-meant commented on configuration/concepts/orthopedics.csv
> +f7d0c35f-5d82-457d-a7f3-91f42720ff26,,Days in Hospital,Days in Hospital,Días en el Hospital,Días en el Hospital,,Misc,Text,,,,
Should this be text or numeric?

2022-03-09 09:35 UTC, basrem commented on configuration/concepts/orthopedics.csv
> +f7d0c35f-5d82-457d-a7f3-91f42720ff26,,Days in Hospital,Days in Hospital,Días en el Hospital,Días en el Hospital,,Misc,Text,,,,
Done making it numeric

2022-03-25 07:42 UTC, reagan-meant requested changes

2022-03-25 07:42 UTC, reagan-meant commented on configuration/concepts/orthopedics.csv
> +83c8f919-5bc8-4507-bf4b-85552cb6eeef,,Parts of the Body/ Bones Affected,Parts of the Body/ Bones Affected,Partes del cuerpo/huesos afectados,Partes del cuerpo/huesos afectados,,Misc,Text,,,,
Change to 'Parts of the Body/Bones Affected'

2022-03-25 07:42 UTC, reagan-meant commented on configuration/concepts/orthopedics.csv
> +6bb7ce1f-1036-46d3-b52e-68d08c496518,,Infections,Infections,Infecciones,Infecciones,,Misc,Coded,Yes; No,,,
Add 'Unknown' answer

2022-04-11 07:56 UTC, merged