GHC-136: Add lab ranges and accept decimals
globalhealthcoalition/openmrs-config-ghc pull request #88
Opened 2022-08-17 08:53 UTC by basrem

2022-09-12 05:23 UTC, reagan-meant commented on configuration/concepts/lab_tests.csv
> +2372438b-3441-4fe2-bb4c-37f3b04b525e,,,Sodium,Sodio,Sodio,Sodium,,LabTest,Numeric,,,,,mEq/L,138,148,,,
Should this also accept decimal places?

2022-09-12 15:13 UTC, basrem commented on configuration/concepts/lab_tests.csv
> +2372438b-3441-4fe2-bb4c-37f3b04b525e,,,Sodium,Sodio,Sodio,Sodium,,LabTest,Numeric,,,,,mEq/L,138,148,,,
Yes it should, fixed it below

2022-09-13 06:00 UTC, reagan-meant requested changes
Use the old uuid of the form

2022-10-03 10:48 UTC, reagan-meant requested changes

2022-10-03 10:48 UTC, reagan-meant commented on configuration/concepts/lab_tests.csv
> +acdc2f09-2844-43e0-9067-8e71da8319ae,,,Urinalysis,Análisis de orina,Análisis de orina,Urinalysis,,LabSet,N/A,,,Aspect;Color;PH; Specific gravity; Glucose; Ketones; Urobilinogen; Nitrites; Leukocyte e
What is the `Yes` for here?

2022-10-06 14:39 UTC, merged